version: 0.2
run-as: root

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 398458635191.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=398458635191.dkr.ecr.us-west-2.amazonaws.com/tf-python-app-repo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t tf-python-app-repo:latest .
      - docker tag tf-python-app-repo:latest 398458635191.dkr.ecr.us-west-2.amazonaws.com/tf-python-app-repo:latest
      - echo scanning image for vunerability
      -  #docker run --rm -v /root/.cache/:/root/.cache/ aquasec/trivy:0.18.3 --exit-code=1 tf-python-app-repo:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 398458635191.dkr.ecr.us-west-2.amazonaws.com/tf-python-app-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' python-app 398458635191.dkr.ecr.us-west-2.amazonaws.com/tf-python-app-repo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
